# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-index:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Autogenerate the index page for the recipes
        run: |
          git config user.email "tux2603@gmail.com"
          git config user.name "GitHub Action Auto Commit"
          which python3
          python3 --version
          python3 scripts/generateIndex.py
          git add recipes/index.md
          git commit -m 'Auto generated recipe index'
          git push origin `git subtree split --prefix=recipes main`:gh-pages --force
