name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize git
        run: |
          git config user.email "tux2603@gmail.com"
          git config user.name "GitHub Action Auto Commit"

      - name: Generate PDFs
        run: |
          docker pull pandoc/alpine-latex
          [ -d recipes/pdf ] || mkdir recipes/pdf
          for i in `find recipes -mindepth 2 -name '*.md'`; do 
            category=$(echo $i | awk -F/ '{print $2}')
            recipe=$(echo $i | awk -F/ '{print $3}' | awk -F. '{print $1}')
            
            [ -d "recipes/pdf/$category" ] || mkdir "recipes/pdf/$category"

            (echo "---"; cat scripts/format.yml; echo -e "\n---\n"; cat "recipes/$category/$recipe.md") >/tmp/recipe.md
            cat /tmp/recipe.md
            docker run --rm -v /tmp:/tmp pandoc/alpine-latex /tmp/recipe.md -t pdf >"recipes/pdf/$category/$recipe.pdf"
            git add "recipes/pdf/$category/$recipe.pdf"
          done
          git commit -m 'Generated pdf files'
          
      - name: Link to PDFs
        run: |
          for i in `find recipes -mindepth 2 -name '*.md'`; do 
            category=$(echo $i | awk -F/ '{print $2}')
            recipe=$(echo $i | awk -F/ '{print $3}' | awk -F. '{print $1}')
            echo -e "\n\n[View PDF](/recipes/pdf/$category/$recipe.pdf)" >>"recipes/$category/$recipe.md"
            git add "recipes/$category/$recipe.md"
          done
          git commit -m 'Add links to PDFs'

      - name: Autogenerate the index page for the recipes
        run: |
          python3 scripts/generateIndex.py
          git add recipes/index.md
          git commit -m 'Generated recipe index'

      - name: Push new files to GitHub pages
        run: |
          git push origin `git subtree split --prefix=recipes main --ignore-join --rejoin`:gh-pages --force
